### ISSUE TITLE
Some question regarding custom training

### ISSUE THREAD

**Issue by VanitarNordic** [twmht/PVANet-FACE#1]
Hello,

Good Job. I have some questions which it will be beneficial for other people who may consider it.

1) How can I train the model on my own custom dataset which may have one two or more classes?
What annotation format I should make? is there any tool to prepare them?

2) How can I use the trained mode on unseen image, videos or live camera (possibly USB camera)?

**Comment by twmht** [comment]
@VanitarNordic 

1. there is a file `lib/dataset/imdb.py` which defines the interface to deal with the dataset. You can create a class which inherits from `imdb.py` and parse on your own dataset. To see an example, you can look at `lib/dataset/wider.py`.

The VOC format has annotations about the locations of bounding boxes within an image, and this is pva-faster-rcnn needed. So in your own dataset, you should embed the locations of bounding boxes into your custom imdb.

2. pva-faster-rcnn is a supervised neural network, it means you need to label each image before training. So, you can not fed unseen image into this network.

**Comment by twmht** [comment]
@VanitarNordic 

to train on the different number of classes, you need to modify the training prototxt in pvaNet. 

For example, if you want to train only one class, then you should change `num_classes in ``models/pvanet/example_train/train.prototxt`  to 2 (1+1). 
and `num_output` in `bbox_pred`  to 8 (2 * 4).

You can see the example change below, where there is only one class.
https://github.com/twmht/PVANet-FACE/commit/04bb256438b0986d049e6adb2c6f08f7a4a11486#diff-e5b96885b1302024afa0337c4f0735c4

**Comment by VanitarNordic** [comment]
> There is a file `lib/dataset/imdb.py` which defines the interface to deal with the dataset. You can create a class which inherits from `imdb.py` and parse on your own dataset. To see an example, you can look at lib/dataset/wider.py.
The VOC format has annotations about the locations of bounding boxes within an image, and this is pva-faster-rcnn needed. So in your own dataset, you should embed the locations of bounding boxes into your custom imdb.

In the VOC format each image file has its on corresponding `.xml` file as annotation. if I understood correctly, a VOC based dataset can be converted to IMDB using `wider.py`

would you please explain more that how should I use this file when I have a dataset with some images and xml annotations. I'm not a python master.

> pva-faster-rcnn is a supervised neural network, it means you need to label each image before training. So, you can not fed unseen image into this network.

I meant to test the trained model `.caffemodel` on unseen image, videos or camera live stream. not using them for training.

**Comment by twmht** [comment]
@VanitarNordic 

you have to look at `tools/convert_wider_to_imdb.py` which convert [WIDERFACE](http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/) dataset into imdb.

I define my imdb dataset as follows, there are two binary files

`image.db` has a sequence of blobs, each blob is represented as a protobuf. 
blob1,blob2,blob3

the protobuf format can be found at https://github.com/twmht/PVANet-FACE/blob/master/lib/datasets/image_format.proto

this protobuf format contains image data and the set of bounding boxes.

the other file is `index.db` which records the position and size of each blob.

If your dataset is XML based and you want to convert to wider format, you have to use xml library to read the xml and extract the bounding boxes. And put the image bytes data into the protobuf.

Here is the pseudo code together with python-protobuf

```
foreach image and xml in your dataset:
    # Here Image is the protobuf format
    image = Image()
    image.name = image_name
    image.data = open(image_name).read()
    image.width = image_width
    image.height = image_height
   foreach bounding box in xml:
        obj = image.objects.add()
        obj.minX = xmin
        obj.minY = ymin
        obj.maxX = xmax
        obj.maxY = ymax   
```

**Comment by VanitarNordic** [comment]
My dataset format is VOC actually, because I found a software to annotate images in VOC format and no need to write a software to annotate them.

is there any tool to annotate images within Protobuf format? (When we want to gather our own images)

**Comment by twmht** [comment]
@VanitarNordic 

If you want to use the protobuf-format, you need to write code to encode them.

If you want to use VOC format, you can reference [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn) and download VOC image dataset via its script.

And then you can see where it locates the VOC image dataset, and you can replace it by your own.
