### ISSUE TITLE
Difference between this repo and the original one

### ISSUE THREAD

**Issue by VanitarNordic** [twmht/PVANet-FACE#2]
Hello,

The original repository mentioned that its published code is not the one which is used by the author and it is slower or less accurate. have you fixed these in your repo?

>Please note that this repository doesn't contain our in-house codes used in the published article.
    This version of py-faster-rcnn is slower than our in-house runtime code (e.g. image pre-processing code written in Python)
    PVANet was trained by our in-house deep learning library, not by this implementation.
    There might be a tiny difference in VOC2012 test results, because some hidden parameters in py-faster-rcnn may be set differently with ours.

**Comment by twmht** [comment]
@VanitarNordic 

this repo  still use the python code to do image pre-processing, the only difference is that I change the data format to speed up the prepare roi data phase.

In short, I did not fix it, this repo does not reproduce the Paper's result.
