### ISSUE TITLE
how long is the running time

### ISSUE THREAD

**Issue by tzhang2014** [twmht/PVANet-FACE#4]
Dear　twmht , I run the demo took 130ms/frame．How long is the running time to you ? THX

**Comment by twmht** [comment]
@tzhang2014 

same.

this is due to the performance of python implementation.

in c++ implementation, the fps is very close to the paper.

**Comment by twmht** [comment]
For people confusing the performance, please use https://github.com/twmht/PVANet-FACE/blob/master/tools/gen_merged_model.py to compress your model.
