### ISSUE TITLE
Compressed model

### ISSUE THREAD

**Issue by pasxalinamed** [twmht/PVANet-FACE#5]
I have trained a model on my own data. How can I compress the output caffemodel? Is compression something that should have taken place during training?

**Comment by twmht** [comment]
please take look at https://github.com/twmht/PVANet-FACE/blob/master/tools/gen_merged_model.py

**Comment by pasxalinamed** [comment]
Thank you for your answer. I run gen_merged_model.py for my prototxt and caffemodel however the output inference model had slower performance (5 fps slower), the caffemodel remained the same size (385.8MB) and detections became completely wrong. Output bounding boxes do not make sense.  :(

**Comment by twmht** [comment]
@pasxalinamed 

Can you post the results after drawing bounding box?

**Comment by pasxalinamed** [comment]
![screenshot from 2017-11-27 13 46 53](https://user-images.githubusercontent.com/17580240/33265256-93ba2ea2-d379-11e7-839d-082302ef9503.png)

![screenshot from 2017-11-27 13 46 26](https://user-images.githubusercontent.com/17580240/33265255-939bd614-d379-11e7-81fc-e04397ff7aec.png)



before the model outputs correct boxes and after not

**Comment by pasxalinamed** [comment]
I used ./tools/compress_net.py and gave as input my prototxt and caffemodel and for the compressed prototxt I gave as input ./models/pvanet_obsolete/comp/oroginal.pt
The result was a model with size 79.6MB from the initial  385.8MB. However speed was only improved by 2fps.
