### ISSUE TITLE
Fail to convert wider to imdb.

### ISSUE THREAD

**Issue by Arthur-Shi** [twmht/PVANet-FACE#6]
I change the path, 
wider_train = WIDER('/home/deep/zl/pva-faster-rcnn/data/wider_face_split',
              '/home/deep/zl/pva-faster-rcnn/data/WIDER_train/images',
              '/home/deep/zl/pva-faster-rcnn/data/wider_face_split/wider_face_train.mat')

But I cannot convert it successfully.
deep@deep:~/zl/pva-faster-rcnn/tools$ sudo python convert_wider_to_imdb.py 
Traceback (most recent call last):
  File "convert_wider_to_imdb.py", line 72, in <module>
    wider_train = WIDER('/home/deep/zl/pva-faster-rcnn/data/wider_face_split','/home/deep/zl/pva-faster-rcnn/data/WIDER_train/images','/home/deep/zl/pva-faster-rcnn/data/wider_face_split/wider_face_train.mat')
  File "/usr/local/lib/python2.7/dist-packages/wider/loader.py", line 16, in __init__
    self.f = h5py.File(os.path.join(path_to_label, fname), 'r')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)

What can I do?

**Comment by twmht** [comment]
Are you sure that the file exists?

**Comment by Arthur-Shi** [comment]
yes,  I double checked, could u tell me where these files should be?
 I downloaded these folders.
 /home/deep/zl/pva-faster-rcnn/data/wider_face_split
/home/deep/zl/pva-faster-rcnn/data/WIDER_test
/home/deep/zl/pva-faster-rcnn/data/WIDER_train
/home/deep/zl/pva-faster-rcnn/data/WIDER_val

and I found three files in these folders. and then copy these paths into convert-wider-to-imdb.py.
